Repository DO-SOPT-APP4-MILLIE/Millie_iOS, pull requests merged in 2023-11, with the labels that each got.

#15 [Feat]#13 투데이 뷰 UI 구현
  Millie_iOS/Millie_iOS.xcodeproj/project.pbxproj
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Fist/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Fist/today_card_week_1.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Fist/today_card_week_1.imageset/today_card_week_1.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Fist/today_card_week_1.imageset/today_card_week_1@2x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Fist/today_card_week_1.imageset/today_card_week_1@3x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Montly/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Montly/today_new_book_01.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Montly/today_new_book_01.imageset/today_new_book_01-2.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Montly/today_new_book_01.imageset/today_new_book_01-3.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Montly/today_new_book_01.imageset/today_new_book_01.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Original/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Original/today_card_original_01.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Original/today_card_original_01.imageset/today_card_original_01-2.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Original/today_card_original_01.imageset/today_card_original_01-3.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Original/today_card_original_01.imageset/today_card_original_01.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Preference/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Preference/today_rec_02.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Preference/today_rec_02.imageset/today_rec_02-2.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Preference/today_rec_02.imageset/today_rec_02-3.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/Preference/today_rec_02.imageset/today_rec_02.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_ic_thumbs_up.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_ic_thumbs_up.imageset/today_ic_thumbs_up.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_ic_thumbs_up.imageset/today_ic_thumbs_up@2x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_ic_thumbs_up.imageset/today_ic_thumbs_up@3x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_best_01.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_best_01.imageset/today_img_best_01.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_best_01.imageset/today_img_best_01@2x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_best_01.imageset/today_img_best_01@3x.png
  Millie_iOS/Millie_iOS/Resource/Constants/Image.swift
  Millie_iOS/Millie_iOS/Resource/Extensions/UIButton+.swift
  Millie_iOS/Millie_iOS/Resource/Extensions/UICollectionView+.swift
  Millie_iOS/Millie_iOS/Resource/Extensions/UILabel+.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayBestCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayFavoriteCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayFistCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayMonthlyCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayOriginalCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayPreferenceCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayTableViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayBestView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayFavoriteView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayFistView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayMonthlyView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayOriginalView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayPreferenceView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/ViewController/TodayViewController.swift
Labels: 🐱지원🐱, Feat

#25 [Feat]#22 투데이뷰 추가 구현
  Millie_iOS/Millie_iOS.xcodeproj/project.pbxproj
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_footer.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_footer.imageset/today_footer.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_footer.imageset/today_footer@2x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_footer.imageset/today_footer@3x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_banner.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_banner.imageset/today_img_banner.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_banner.imageset/today_img_banner@2x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/Today/today_img_banner.imageset/today_img_banner@3x.png
  Millie_iOS/Millie_iOS/Resource/Constants/Image.swift
  Millie_iOS/Millie_iOS/Resource/Extensions/Adjust+.swift
  Millie_iOS/Millie_iOS/Resource/Extensions/MillieTagView.swift
  Millie_iOS/Millie_iOS/Source/Data/Today/TodayOriginalTagDummy.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayBestCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayFavoriteCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayFistCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayMonthlyCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayOriginalCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayOriginalTagCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayPreferenceCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayPreferenceTagCollectionViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/Cell/TodayTableViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/HeaderFooterView/TodayFooterView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/HeaderFooterView/TodayHeaderView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayBestView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayFavoriteView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayFistView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayMonthlyView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayOriginalView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayPreferenceView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/View/TodayView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Today/ViewController/TodayViewController.swift
Labels: 🐱지원🐱, Feat, Fix

#23 Chore(#21): 상세 뷰 ScrollView height 고정값 삭제, 동적으로 스크롤뷰 구현
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailBookDescriptionView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailMoreDescriptionView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailPopularView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailSelectCategoryView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailWandokView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailWeeklyBestBookView.swift
Labels: 🐢상우🐢, Feat

#27 [Feat] #20 - 상세 팝업 뷰 UI 구현
  Millie_iOS/Millie_iOS.xcodeproj/project.pbxproj
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/ViewController/DetailViewController.swift
  Millie_iOS/Millie_iOS/Source/Presentation/DetailPopup/View/DetailPopupMyFavoriteView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/DetailPopup/View/DetailPopupView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/DetailPopup/ViewController/DetailPopupViewController.swift
Labels: 🐰효원🐰, Feat

#30 [Network]#29 네트워크 세팅
  Millie_iOS/Millie_iOS.xcodeproj/project.pbxproj
  Millie_iOS/Millie_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Millie_iOS/Millie_iOS/Resource/Constants/Config.swift
  Millie_iOS/Millie_iOS/Resource/Constants/URLs.swift
  Millie_iOS/Millie_iOS/Source/Network/NetworkResult.swift
Labels: 🐱지원🐱, Network, Setting

#37 [Feat]#35 상세뷰 API 연결 완료
  Millie_iOS/Millie_iOS.xcodeproj/project.pbxproj
  Millie_iOS/Millie_iOS/Resource/Constants/URLs.swift
  Millie_iOS/Millie_iOS/Source/Network/Detail/DetailBody.swift
  Millie_iOS/Millie_iOS/Source/Network/Detail/DetailService.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailBookDescriptionView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/View/DetailWandokView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Detail/ViewController/DetailViewController.swift
Labels: 🐢상우🐢, Network

#38 Network(#33): 베스트뷰 도서 리스트 api 연동
  Millie_iOS/Millie_iOS.xcodeproj/project.pbxproj
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_down.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_down.imageset/Polygon 2.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_down.imageset/Polygon 2@2x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_down.imageset/Polygon 2@3x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_up.imageset/Contents.json
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_up.imageset/Polygon 2.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_up.imageset/Polygon 2@2x.png
  Millie_iOS/Millie_iOS/Resource/Assets.xcassets/ic_rank_up.imageset/Polygon 2@3x.png
  Millie_iOS/Millie_iOS/Resource/Constants/Image.swift
  Millie_iOS/Millie_iOS/Source/Data/BestModel/BestModel.swift
  Millie_iOS/Millie_iOS/Source/Data/BestModel/BooksDummy.swift
  Millie_iOS/Millie_iOS/Source/Network/Best/BestAPI.swift
  Millie_iOS/Millie_iOS/Source/Network/Best/BestService.swift
  Millie_iOS/Millie_iOS/Source/Network/GenericResponse.swift
  Millie_iOS/Millie_iOS/Source/Network/MoyaLoggerPlugin.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Best/Cell/BestTableViewCell.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Best/View/BestView.swift
  Millie_iOS/Millie_iOS/Source/Presentation/Best/ViewController/BestViewController.swift
Labels: 🐰효원🐰, Network
